version: "3.1"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - python-app

  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "8001:3000"
    volumes:
      - ./node-app:/home/app
    command: ["npm", "run", "dev"]

  php:
    image: webdevops/php-apache-dev:8.2
    volumes:
      - ./php-app:/app
    ports:
      - "8002:80"
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  python-app:
    image: python:3.11-slim
    working_dir: /app
    restart: always
    volumes:
      - ./python-app:/app
    ports:
      - "8003:5000"
    command: >
      bash -c "pip install -r /app/requirements.txt && flask run --host=0.0.0.0 --port=5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
